## 📊 Introdução ao Numpy 

<img src="https://shre.ink/numpy1" width=400>

### Porque Numpy

- "Numpy" usa array, que são como listas especiais, onde todos itens são do mesmo tipo. Ele pode ter diferentes formatos e tamanhos, dependendo da necessidade, normalmente usamos arrays de até 3 dimensões (Como uma tabela 3D), mas é possivel ter mais. No python, pode imaginar dimensões como "listas dentro de listas".
<img src="https://shre.ink/numpy2" width=500>
- O Numpy, permite guardar dados e manipula-los no formato de matrizes. Elas podem ser infinitamente dimensionais, por isso é importante que tenha noção de como esses dados são armazenados, para que possa manipula-los de maneira correta.
---
<img src="https://shre.ink/numpy3" width=458>

<img src="https://shre.ink/numpy4" width=500>

~~~python
# Para usar o Numpy, no Script

import numpy as np

In [ ]:
%pip freeze

In [ ]:
%pip install numpy

### Qual a diferença de listas e array NumPy

Lista do Python e arrays do NumPy tem algumas em comum:
- Guardam varios elementos em sequencia
- Permite adicionar, remover, concatenar elementos

Mas os arrays NumPy têm algumas vantagens bem importantes:
- São mais rapidas e eficentes em operações matemáticas
- Usam menos memórias
- Tem varias ferramentas extras para trabalhar com dados numéricos

**Resumindo** Listas são mais flexíveis, mas os arrays do NumPy, são melhores quando o foco são numeros e cálculos

- Operações Matematicas: O array do Numpy, faz conta de uma vez em todos os elementos (vetorial), já lista do python faz item por item (escalar)

In [ ]:
lista = [1,2,3]

print("Resultado da Operação multiplicação")
print(lista*2)

In [ ]:
a = [1,3,5]
b = [5,7,9]

In [ ]:
valor = []
for i in range(3):
    valor.append(a[i] * b[i])
print(valor)

### Criando Array Numpy

- A base do numpy são os array, que guardam dados do mesmo tipo e podem ter varias dimensões.
- Você pode criar arrays a partir de uma lista comum do python

In [ ]:
import numpy as np

# Isso é uma lista
lista = [10,20,30,40]

array = np.array(lista)

print(f"Lista: {lista}, tipo: {type(lista)}")
print(f"Array: {array}, tipo: {type(array)}")

### Array 1d: Vetores

---
1. Array Numpy de uma dimensão (1d) são conhecidas como **vetores** como listas, de uma linha ou de mais colunas

- Criação

In [ ]:
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([10,20,30,40,50,60], dtype='int8')
print(f'Meu array {a1}')

### Usando atributo ndim, que é utilizado para descrever as dimensões do array

In [ ]:
print(f'dimensão do array a1: {a1.ndim}')

### O tamanho do array

In [ ]:
print(f'Tamanho do Array a1: {a1.shape}')

### Tipo de dados do Array

In [ ]:
print(f'Tipos de dados dentro do Array a1: {a1.dtype}')
print(f'Tipos de dados dentro do Array a2: {a2.dtype}')

### Array com uma sequencia de zero a nove

In [ ]:
a2 = np.arange(10)
print(f'Meu array {a2}')

### Array com sequencia de dez "zeros"

In [ ]:
zeros = np.zeros(10)
print(f"O meu array com zeros: {zeros}")

In [ ]:
uns = np.ones(10)
print(f"O meu array com uns: {uns}")

### Array com sequencia de numeros aleatórios

In [ ]:
np.random.seed(1)
aleatorio = np.random.randint(1,100,10)
print(f'Meu Array: {aleatorio}')

In [ ]:
a4= np.random.random(10)
print(f'Meu array: {a4}')

### Funções Elementares
---
- Soma

In [ ]:
array_a = np.array([1,2,3,4,5])
array_b = np.array([10,20,30,40,50])
escalar = 5

#Soma de Arrays
print(f'Soma de Arrays (operador +): {array_a + array_b}')
print(f'Soma de Arrays com variavel (operador +): {array_a + escalar}')


---
- Subtração

In [ ]:
print(f'Subtração de Arrays (operador -): {array_a - array_b}')
print(f'Subtração de Arrays com variavel (operador -): {array_a - escalar}')

---
- Divisão

In [ ]:
print(f'Divisão de Arrays (operador /): {array_a / array_b}')
print(f'Divisão de Arrays com variavel (operador /): {array_b / escalar}')

---
- Multiplicação

In [ ]:
print(f'Multiplicação de Arrays (operador *): {array_a * array_b}')
print(f'Multiplicação de Arrays com variavel (operador *): {array_a * escalar}')

----
- Exponenciação

In [ ]:
print(f'Exponenciação de Arrays (operador **): {array_b ** array_a}')
print(f'Exponenciação de Arrays com variavel (operador **): {array_a ** escalar}')

### Desafio

1. Array 1d
---
a) Crie um array numpy chamado **vetor** com os numeros 10 a 50, de 10 em 10

b) Imprima o array

c) Imprima o Tamanho desse array

d) Imprima apenas os 3 primeiros elementos usando slicing

e)Imprima os dois ultimos elementos usando slicing

In [ ]:
vetor = np.arange(10,51,10)
print(f"Meu array: {vetor}")
print(f"O tamanho é: {vetor.shape}")
print(f"O recorte dos 3 primeiros: {vetor[:3]}")
print(f"O recorte dos 2 ultimos: {vetor[-2:]}")

### Arrays 2D: Matrizes
---

- Array Numpy de 2 dimensões (2D) são conhecidas como **matrizes**, como tabelas, com linhas e colunas.

#### Criação

~~~python
import numpy as np

In [2]:
import numpy as np

m1 = np.array([
    [40,50,60],
    [70, 80, 90]
])

print(m1)
print(f"Formato do Array: {m1.shape}")
print(f"Dimensão do Array: {m1.ndim}")
print(f"Tipo do Array: {m1.dtype}")

[[40 50 60]
 [70 80 90]]
Formato do Array: (2, 3)
Dimensão do Array: 2
Tipo do Array: int64


In [ ]:
m2 = np.array([[2,3,4,5],[9,8,7,6],[50,60,70,60]])
print(m2)
print(f"Formato do Array: {m2.shape}")
print(f"Dimensão do Array: {m2.ndim}")
print(f"Tipo do Array: {m2.dtype}")

In [ ]:
print(m2[1, 1:3])
print(m2[0])
print(m2[2])

print(m2[:,1:3]) #Coluna

In [ ]:
m3 = np.ones([5,7])
print(m3)

### Crie um array com os numeros de 1 a 5 e imprima cada elemento usando um loop

In [ ]:
numeros = np.array([[1,2,3],[4,5,6]])

a,b = numeros.shape

for i in range(a):
    for y in range(b):
        print(numeros[i,y], end=' ')
    print()


In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])

matriz[1,1]=50
print(matriz[1,1])

In [ ]:
#Teste

matriz_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

matriz_4d = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

In [130]:
#Numeros / Aleatórios

np.full([3,3],50+1)

array([[51, 51, 51],
       [51, 51, 51],
       [51, 51, 51]])

In [ ]:
np.full_like(matriz_4d,8)

In [81]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
vetor = np.array([[1,2,3]])

np.repeat(vetor,3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

5 5 5 5 5
3 0 0 0 3
3 0 15 0 3
3 0 0 0 3
3 3 3 3 3

In [3]:
matriz = np.full([5,5],0)
matriz[0] = 5
matriz[-1] = 3
matriz[1:,0] = 3
matriz[1:,-1] = 3
matriz[2,2] = 15
#matriz[2,2] = matriz[0,0]*matriz[-1,-1]

print(matriz[1:-1,1:-1])


[[ 0  0  0]
 [ 0 15  0]
 [ 0  0  0]]
